# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-22 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MontrealGazetteArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('original_text', models.TextField()),
                ('modified_text', models.TextField()),
            ],
        ),
    ]
